variables:
  BUILD_STABLE_REGISTRY: registry.ddbuild.io
  CI_IMAGE_REPO: "ci/${CI_PROJECT_NAME}"
  CI_REGISTRY_IMAGE: "$BUILD_STABLE_REGISTRY/$CI_IMAGE_REPO/runner"
  CI_REGISTRY_IMAGE_TEST: "$BUILD_STABLE_REGISTRY/$CI_IMAGE_REPO/runner-dev"

stages:
  - build
  - release

build-runner-image:
  stage: build
  image: ${BUILD_STABLE_REGISTRY}/images/docker:27.3.1
  tags: ["arch:amd64"]
  variables:
    RELEASE_IMAGE: "false"
  rules:
    - when: on_success
  before_script:
    - set +x
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install
    - export GITHUB_APP_ID=$(aws ssm get-parameter --region us-east-1 --name ci.test-infra-definitions.github_app_id --with-decryption --query "Parameter.Value" --out text)
    - export GITHUB_INSTALLATION_ID=$(aws ssm get-parameter --region us-east-1 --name ci.test-infra-definitions.github_installation_id --with-decryption --query "Parameter.Value" --out text)
    - export GITHUB_PRIVATE_KEY=$(aws ssm get-parameter --region us-east-1 --name ci.test-infra-definitions.github_private_key --with-decryption --query "Parameter.Value" --out text)
    - export JWT=$(.github/jwt.sh "$GITHUB_APP_ID" <(echo "$GITHUB_PRIVATE_KEY"))
    - |
      export GITHUB_TOKEN=`curl -s --fail --retry 10 -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $JWT" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/app/installations/$GITHUB_INSTALLATION_ID/access_tokens | jq -r '.token'`
  script:
    - METADATA_FILE=$(mktemp)
    - docker buildx build --no-cache --pull --push --label target=build --tag ${CI_REGISTRY_IMAGE_TEST}:${CI_COMMIT_SHORT_SHA} --tag ${CI_REGISTRY_IMAGE_TEST}:${CI_COMMIT_SHA:0:12} --secret id=github_token,env=GITHUB_TOKEN --metadata-file "${METADATA_FILE}" .
    - ddsign sign "${CI_REGISTRY_IMAGE_TEST}:${CI_COMMIT_SHORT_SHA}" --docker-metadata-file "${METADATA_FILE}"
    - ddsign sign "${CI_REGISTRY_IMAGE_TEST}:${CI_COMMIT_SHORT_SHA:0:12}" --docker-metadata-file "${METADATA_FILE}"
  retry: 2

release-runner-image:
  stage: release
  image: ${BUILD_STABLE_REGISTRY}/images/docker:27.3.1
  tags: ["arch:amd64"]
  script:
    - crane copy ${CI_REGISTRY_IMAGE_TEST}:${CI_COMMIT_SHORT_SHA} ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA:0:12}
    - DIGEST=$(crane digest ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA:0:12})
    - ddsign sign "${CI_REGISTRY_IMAGE_TEST}:${CI_COMMIT_SHORT_SHA:0:12}@${DIGEST}"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: on_success
