// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = utilities.GetEnvOrDefault

// DatadogMetric allows autoscaling on arbitrary Datadog query
type DatadogMetricType struct {
	ApiVersion *string            `pulumi:"apiVersion"`
	Kind       *string            `pulumi:"kind"`
	Metadata   *metav1.ObjectMeta `pulumi:"metadata"`
	// DatadogMetricSpec defines the desired state of DatadogMetric
	Spec *DatadogMetricSpec `pulumi:"spec"`
	// DatadogMetricStatus defines the observed state of DatadogMetric
	Status *DatadogMetricStatus `pulumi:"status"`
}

type DatadogMetricMetadata struct {
}

// DatadogMetricSpec defines the desired state of DatadogMetric
type DatadogMetricSpec struct {
	// ExternalMetricName is reserved for internal use
	ExternalMetricName *string `pulumi:"externalMetricName"`
	// MaxAge provides the max age for the metric query (overrides the default setting `external_metrics_provider.max_age`)
	MaxAge *string `pulumi:"maxAge"`
	// Query is the raw datadog query
	Query *string `pulumi:"query"`
	// TimeWindow provides the time window for the metric query, defaults to MaxAge.
	TimeWindow *string `pulumi:"timeWindow"`
}

// DatadogMetricSpecInput is an input type that accepts DatadogMetricSpecArgs and DatadogMetricSpecOutput values.
// You can construct a concrete instance of `DatadogMetricSpecInput` via:
//
//	DatadogMetricSpecArgs{...}
type DatadogMetricSpecInput interface {
	pulumi.Input

	ToDatadogMetricSpecOutput() DatadogMetricSpecOutput
	ToDatadogMetricSpecOutputWithContext(context.Context) DatadogMetricSpecOutput
}

// DatadogMetricSpec defines the desired state of DatadogMetric
type DatadogMetricSpecArgs struct {
	// ExternalMetricName is reserved for internal use
	ExternalMetricName pulumi.StringPtrInput `pulumi:"externalMetricName"`
	// MaxAge provides the max age for the metric query (overrides the default setting `external_metrics_provider.max_age`)
	MaxAge pulumi.StringPtrInput `pulumi:"maxAge"`
	// Query is the raw datadog query
	Query pulumi.StringPtrInput `pulumi:"query"`
	// TimeWindow provides the time window for the metric query, defaults to MaxAge.
	TimeWindow pulumi.StringPtrInput `pulumi:"timeWindow"`
}

func (DatadogMetricSpecArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*DatadogMetricSpec)(nil)).Elem()
}

func (i DatadogMetricSpecArgs) ToDatadogMetricSpecOutput() DatadogMetricSpecOutput {
	return i.ToDatadogMetricSpecOutputWithContext(context.Background())
}

func (i DatadogMetricSpecArgs) ToDatadogMetricSpecOutputWithContext(ctx context.Context) DatadogMetricSpecOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatadogMetricSpecOutput)
}

func (i DatadogMetricSpecArgs) ToDatadogMetricSpecPtrOutput() DatadogMetricSpecPtrOutput {
	return i.ToDatadogMetricSpecPtrOutputWithContext(context.Background())
}

func (i DatadogMetricSpecArgs) ToDatadogMetricSpecPtrOutputWithContext(ctx context.Context) DatadogMetricSpecPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatadogMetricSpecOutput).ToDatadogMetricSpecPtrOutputWithContext(ctx)
}

// DatadogMetricSpecPtrInput is an input type that accepts DatadogMetricSpecArgs, DatadogMetricSpecPtr and DatadogMetricSpecPtrOutput values.
// You can construct a concrete instance of `DatadogMetricSpecPtrInput` via:
//
//	        DatadogMetricSpecArgs{...}
//
//	or:
//
//	        nil
type DatadogMetricSpecPtrInput interface {
	pulumi.Input

	ToDatadogMetricSpecPtrOutput() DatadogMetricSpecPtrOutput
	ToDatadogMetricSpecPtrOutputWithContext(context.Context) DatadogMetricSpecPtrOutput
}

type datadogMetricSpecPtrType DatadogMetricSpecArgs

func DatadogMetricSpecPtr(v *DatadogMetricSpecArgs) DatadogMetricSpecPtrInput {
	return (*datadogMetricSpecPtrType)(v)
}

func (*datadogMetricSpecPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**DatadogMetricSpec)(nil)).Elem()
}

func (i *datadogMetricSpecPtrType) ToDatadogMetricSpecPtrOutput() DatadogMetricSpecPtrOutput {
	return i.ToDatadogMetricSpecPtrOutputWithContext(context.Background())
}

func (i *datadogMetricSpecPtrType) ToDatadogMetricSpecPtrOutputWithContext(ctx context.Context) DatadogMetricSpecPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatadogMetricSpecPtrOutput)
}

// DatadogMetricSpec defines the desired state of DatadogMetric
type DatadogMetricSpecOutput struct{ *pulumi.OutputState }

func (DatadogMetricSpecOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DatadogMetricSpec)(nil)).Elem()
}

func (o DatadogMetricSpecOutput) ToDatadogMetricSpecOutput() DatadogMetricSpecOutput {
	return o
}

func (o DatadogMetricSpecOutput) ToDatadogMetricSpecOutputWithContext(ctx context.Context) DatadogMetricSpecOutput {
	return o
}

func (o DatadogMetricSpecOutput) ToDatadogMetricSpecPtrOutput() DatadogMetricSpecPtrOutput {
	return o.ToDatadogMetricSpecPtrOutputWithContext(context.Background())
}

func (o DatadogMetricSpecOutput) ToDatadogMetricSpecPtrOutputWithContext(ctx context.Context) DatadogMetricSpecPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v DatadogMetricSpec) *DatadogMetricSpec {
		return &v
	}).(DatadogMetricSpecPtrOutput)
}

// ExternalMetricName is reserved for internal use
func (o DatadogMetricSpecOutput) ExternalMetricName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DatadogMetricSpec) *string { return v.ExternalMetricName }).(pulumi.StringPtrOutput)
}

// MaxAge provides the max age for the metric query (overrides the default setting `external_metrics_provider.max_age`)
func (o DatadogMetricSpecOutput) MaxAge() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DatadogMetricSpec) *string { return v.MaxAge }).(pulumi.StringPtrOutput)
}

// Query is the raw datadog query
func (o DatadogMetricSpecOutput) Query() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DatadogMetricSpec) *string { return v.Query }).(pulumi.StringPtrOutput)
}

// TimeWindow provides the time window for the metric query, defaults to MaxAge.
func (o DatadogMetricSpecOutput) TimeWindow() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DatadogMetricSpec) *string { return v.TimeWindow }).(pulumi.StringPtrOutput)
}

type DatadogMetricSpecPtrOutput struct{ *pulumi.OutputState }

func (DatadogMetricSpecPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DatadogMetricSpec)(nil)).Elem()
}

func (o DatadogMetricSpecPtrOutput) ToDatadogMetricSpecPtrOutput() DatadogMetricSpecPtrOutput {
	return o
}

func (o DatadogMetricSpecPtrOutput) ToDatadogMetricSpecPtrOutputWithContext(ctx context.Context) DatadogMetricSpecPtrOutput {
	return o
}

func (o DatadogMetricSpecPtrOutput) Elem() DatadogMetricSpecOutput {
	return o.ApplyT(func(v *DatadogMetricSpec) DatadogMetricSpec {
		if v != nil {
			return *v
		}
		var ret DatadogMetricSpec
		return ret
	}).(DatadogMetricSpecOutput)
}

// ExternalMetricName is reserved for internal use
func (o DatadogMetricSpecPtrOutput) ExternalMetricName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DatadogMetricSpec) *string {
		if v == nil {
			return nil
		}
		return v.ExternalMetricName
	}).(pulumi.StringPtrOutput)
}

// MaxAge provides the max age for the metric query (overrides the default setting `external_metrics_provider.max_age`)
func (o DatadogMetricSpecPtrOutput) MaxAge() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DatadogMetricSpec) *string {
		if v == nil {
			return nil
		}
		return v.MaxAge
	}).(pulumi.StringPtrOutput)
}

// Query is the raw datadog query
func (o DatadogMetricSpecPtrOutput) Query() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DatadogMetricSpec) *string {
		if v == nil {
			return nil
		}
		return v.Query
	}).(pulumi.StringPtrOutput)
}

// TimeWindow provides the time window for the metric query, defaults to MaxAge.
func (o DatadogMetricSpecPtrOutput) TimeWindow() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DatadogMetricSpec) *string {
		if v == nil {
			return nil
		}
		return v.TimeWindow
	}).(pulumi.StringPtrOutput)
}

// DatadogMetricStatus defines the observed state of DatadogMetric
type DatadogMetricStatus struct {
	// List of autoscalers currently using this DatadogMetric
	AutoscalerReferences *string `pulumi:"autoscalerReferences"`
	// Conditions Represents the latest available observations of a DatadogMetric's current state.
	Conditions []DatadogMetricStatusConditions `pulumi:"conditions"`
	// Value is the latest value of the metric
	CurrentValue string `pulumi:"currentValue"`
}

// DatadogMetricStatusInput is an input type that accepts DatadogMetricStatusArgs and DatadogMetricStatusOutput values.
// You can construct a concrete instance of `DatadogMetricStatusInput` via:
//
//	DatadogMetricStatusArgs{...}
type DatadogMetricStatusInput interface {
	pulumi.Input

	ToDatadogMetricStatusOutput() DatadogMetricStatusOutput
	ToDatadogMetricStatusOutputWithContext(context.Context) DatadogMetricStatusOutput
}

// DatadogMetricStatus defines the observed state of DatadogMetric
type DatadogMetricStatusArgs struct {
	// List of autoscalers currently using this DatadogMetric
	AutoscalerReferences pulumi.StringPtrInput `pulumi:"autoscalerReferences"`
	// Conditions Represents the latest available observations of a DatadogMetric's current state.
	Conditions DatadogMetricStatusConditionsArrayInput `pulumi:"conditions"`
	// Value is the latest value of the metric
	CurrentValue pulumi.StringInput `pulumi:"currentValue"`
}

func (DatadogMetricStatusArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*DatadogMetricStatus)(nil)).Elem()
}

func (i DatadogMetricStatusArgs) ToDatadogMetricStatusOutput() DatadogMetricStatusOutput {
	return i.ToDatadogMetricStatusOutputWithContext(context.Background())
}

func (i DatadogMetricStatusArgs) ToDatadogMetricStatusOutputWithContext(ctx context.Context) DatadogMetricStatusOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatadogMetricStatusOutput)
}

func (i DatadogMetricStatusArgs) ToDatadogMetricStatusPtrOutput() DatadogMetricStatusPtrOutput {
	return i.ToDatadogMetricStatusPtrOutputWithContext(context.Background())
}

func (i DatadogMetricStatusArgs) ToDatadogMetricStatusPtrOutputWithContext(ctx context.Context) DatadogMetricStatusPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatadogMetricStatusOutput).ToDatadogMetricStatusPtrOutputWithContext(ctx)
}

// DatadogMetricStatusPtrInput is an input type that accepts DatadogMetricStatusArgs, DatadogMetricStatusPtr and DatadogMetricStatusPtrOutput values.
// You can construct a concrete instance of `DatadogMetricStatusPtrInput` via:
//
//	        DatadogMetricStatusArgs{...}
//
//	or:
//
//	        nil
type DatadogMetricStatusPtrInput interface {
	pulumi.Input

	ToDatadogMetricStatusPtrOutput() DatadogMetricStatusPtrOutput
	ToDatadogMetricStatusPtrOutputWithContext(context.Context) DatadogMetricStatusPtrOutput
}

type datadogMetricStatusPtrType DatadogMetricStatusArgs

func DatadogMetricStatusPtr(v *DatadogMetricStatusArgs) DatadogMetricStatusPtrInput {
	return (*datadogMetricStatusPtrType)(v)
}

func (*datadogMetricStatusPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**DatadogMetricStatus)(nil)).Elem()
}

func (i *datadogMetricStatusPtrType) ToDatadogMetricStatusPtrOutput() DatadogMetricStatusPtrOutput {
	return i.ToDatadogMetricStatusPtrOutputWithContext(context.Background())
}

func (i *datadogMetricStatusPtrType) ToDatadogMetricStatusPtrOutputWithContext(ctx context.Context) DatadogMetricStatusPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatadogMetricStatusPtrOutput)
}

// DatadogMetricStatus defines the observed state of DatadogMetric
type DatadogMetricStatusOutput struct{ *pulumi.OutputState }

func (DatadogMetricStatusOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DatadogMetricStatus)(nil)).Elem()
}

func (o DatadogMetricStatusOutput) ToDatadogMetricStatusOutput() DatadogMetricStatusOutput {
	return o
}

func (o DatadogMetricStatusOutput) ToDatadogMetricStatusOutputWithContext(ctx context.Context) DatadogMetricStatusOutput {
	return o
}

func (o DatadogMetricStatusOutput) ToDatadogMetricStatusPtrOutput() DatadogMetricStatusPtrOutput {
	return o.ToDatadogMetricStatusPtrOutputWithContext(context.Background())
}

func (o DatadogMetricStatusOutput) ToDatadogMetricStatusPtrOutputWithContext(ctx context.Context) DatadogMetricStatusPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v DatadogMetricStatus) *DatadogMetricStatus {
		return &v
	}).(DatadogMetricStatusPtrOutput)
}

// List of autoscalers currently using this DatadogMetric
func (o DatadogMetricStatusOutput) AutoscalerReferences() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DatadogMetricStatus) *string { return v.AutoscalerReferences }).(pulumi.StringPtrOutput)
}

// Conditions Represents the latest available observations of a DatadogMetric's current state.
func (o DatadogMetricStatusOutput) Conditions() DatadogMetricStatusConditionsArrayOutput {
	return o.ApplyT(func(v DatadogMetricStatus) []DatadogMetricStatusConditions { return v.Conditions }).(DatadogMetricStatusConditionsArrayOutput)
}

// Value is the latest value of the metric
func (o DatadogMetricStatusOutput) CurrentValue() pulumi.StringOutput {
	return o.ApplyT(func(v DatadogMetricStatus) string { return v.CurrentValue }).(pulumi.StringOutput)
}

type DatadogMetricStatusPtrOutput struct{ *pulumi.OutputState }

func (DatadogMetricStatusPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DatadogMetricStatus)(nil)).Elem()
}

func (o DatadogMetricStatusPtrOutput) ToDatadogMetricStatusPtrOutput() DatadogMetricStatusPtrOutput {
	return o
}

func (o DatadogMetricStatusPtrOutput) ToDatadogMetricStatusPtrOutputWithContext(ctx context.Context) DatadogMetricStatusPtrOutput {
	return o
}

func (o DatadogMetricStatusPtrOutput) Elem() DatadogMetricStatusOutput {
	return o.ApplyT(func(v *DatadogMetricStatus) DatadogMetricStatus {
		if v != nil {
			return *v
		}
		var ret DatadogMetricStatus
		return ret
	}).(DatadogMetricStatusOutput)
}

// List of autoscalers currently using this DatadogMetric
func (o DatadogMetricStatusPtrOutput) AutoscalerReferences() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DatadogMetricStatus) *string {
		if v == nil {
			return nil
		}
		return v.AutoscalerReferences
	}).(pulumi.StringPtrOutput)
}

// Conditions Represents the latest available observations of a DatadogMetric's current state.
func (o DatadogMetricStatusPtrOutput) Conditions() DatadogMetricStatusConditionsArrayOutput {
	return o.ApplyT(func(v *DatadogMetricStatus) []DatadogMetricStatusConditions {
		if v == nil {
			return nil
		}
		return v.Conditions
	}).(DatadogMetricStatusConditionsArrayOutput)
}

// Value is the latest value of the metric
func (o DatadogMetricStatusPtrOutput) CurrentValue() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DatadogMetricStatus) *string {
		if v == nil {
			return nil
		}
		return &v.CurrentValue
	}).(pulumi.StringPtrOutput)
}

// DatadogMetricCondition describes the state of a DatadogMetric at a certain point.
type DatadogMetricStatusConditions struct {
	// Last time the condition transitioned from one status to another.
	LastTransitionTime *string `pulumi:"lastTransitionTime"`
	// Last time the condition was updated.
	LastUpdateTime *string `pulumi:"lastUpdateTime"`
	// A human readable message indicating details about the transition.
	Message *string `pulumi:"message"`
	// The reason for the condition's last transition.
	Reason *string `pulumi:"reason"`
	// Status of the condition, one of True, False, Unknown.
	Status string `pulumi:"status"`
	// Type of DatadogMetric condition.
	Type string `pulumi:"type"`
}

// DatadogMetricStatusConditionsInput is an input type that accepts DatadogMetricStatusConditionsArgs and DatadogMetricStatusConditionsOutput values.
// You can construct a concrete instance of `DatadogMetricStatusConditionsInput` via:
//
//	DatadogMetricStatusConditionsArgs{...}
type DatadogMetricStatusConditionsInput interface {
	pulumi.Input

	ToDatadogMetricStatusConditionsOutput() DatadogMetricStatusConditionsOutput
	ToDatadogMetricStatusConditionsOutputWithContext(context.Context) DatadogMetricStatusConditionsOutput
}

// DatadogMetricCondition describes the state of a DatadogMetric at a certain point.
type DatadogMetricStatusConditionsArgs struct {
	// Last time the condition transitioned from one status to another.
	LastTransitionTime pulumi.StringPtrInput `pulumi:"lastTransitionTime"`
	// Last time the condition was updated.
	LastUpdateTime pulumi.StringPtrInput `pulumi:"lastUpdateTime"`
	// A human readable message indicating details about the transition.
	Message pulumi.StringPtrInput `pulumi:"message"`
	// The reason for the condition's last transition.
	Reason pulumi.StringPtrInput `pulumi:"reason"`
	// Status of the condition, one of True, False, Unknown.
	Status pulumi.StringInput `pulumi:"status"`
	// Type of DatadogMetric condition.
	Type pulumi.StringInput `pulumi:"type"`
}

func (DatadogMetricStatusConditionsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*DatadogMetricStatusConditions)(nil)).Elem()
}

func (i DatadogMetricStatusConditionsArgs) ToDatadogMetricStatusConditionsOutput() DatadogMetricStatusConditionsOutput {
	return i.ToDatadogMetricStatusConditionsOutputWithContext(context.Background())
}

func (i DatadogMetricStatusConditionsArgs) ToDatadogMetricStatusConditionsOutputWithContext(ctx context.Context) DatadogMetricStatusConditionsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatadogMetricStatusConditionsOutput)
}

// DatadogMetricStatusConditionsArrayInput is an input type that accepts DatadogMetricStatusConditionsArray and DatadogMetricStatusConditionsArrayOutput values.
// You can construct a concrete instance of `DatadogMetricStatusConditionsArrayInput` via:
//
//	DatadogMetricStatusConditionsArray{ DatadogMetricStatusConditionsArgs{...} }
type DatadogMetricStatusConditionsArrayInput interface {
	pulumi.Input

	ToDatadogMetricStatusConditionsArrayOutput() DatadogMetricStatusConditionsArrayOutput
	ToDatadogMetricStatusConditionsArrayOutputWithContext(context.Context) DatadogMetricStatusConditionsArrayOutput
}

type DatadogMetricStatusConditionsArray []DatadogMetricStatusConditionsInput

func (DatadogMetricStatusConditionsArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]DatadogMetricStatusConditions)(nil)).Elem()
}

func (i DatadogMetricStatusConditionsArray) ToDatadogMetricStatusConditionsArrayOutput() DatadogMetricStatusConditionsArrayOutput {
	return i.ToDatadogMetricStatusConditionsArrayOutputWithContext(context.Background())
}

func (i DatadogMetricStatusConditionsArray) ToDatadogMetricStatusConditionsArrayOutputWithContext(ctx context.Context) DatadogMetricStatusConditionsArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatadogMetricStatusConditionsArrayOutput)
}

// DatadogMetricCondition describes the state of a DatadogMetric at a certain point.
type DatadogMetricStatusConditionsOutput struct{ *pulumi.OutputState }

func (DatadogMetricStatusConditionsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DatadogMetricStatusConditions)(nil)).Elem()
}

func (o DatadogMetricStatusConditionsOutput) ToDatadogMetricStatusConditionsOutput() DatadogMetricStatusConditionsOutput {
	return o
}

func (o DatadogMetricStatusConditionsOutput) ToDatadogMetricStatusConditionsOutputWithContext(ctx context.Context) DatadogMetricStatusConditionsOutput {
	return o
}

// Last time the condition transitioned from one status to another.
func (o DatadogMetricStatusConditionsOutput) LastTransitionTime() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DatadogMetricStatusConditions) *string { return v.LastTransitionTime }).(pulumi.StringPtrOutput)
}

// Last time the condition was updated.
func (o DatadogMetricStatusConditionsOutput) LastUpdateTime() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DatadogMetricStatusConditions) *string { return v.LastUpdateTime }).(pulumi.StringPtrOutput)
}

// A human readable message indicating details about the transition.
func (o DatadogMetricStatusConditionsOutput) Message() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DatadogMetricStatusConditions) *string { return v.Message }).(pulumi.StringPtrOutput)
}

// The reason for the condition's last transition.
func (o DatadogMetricStatusConditionsOutput) Reason() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DatadogMetricStatusConditions) *string { return v.Reason }).(pulumi.StringPtrOutput)
}

// Status of the condition, one of True, False, Unknown.
func (o DatadogMetricStatusConditionsOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v DatadogMetricStatusConditions) string { return v.Status }).(pulumi.StringOutput)
}

// Type of DatadogMetric condition.
func (o DatadogMetricStatusConditionsOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v DatadogMetricStatusConditions) string { return v.Type }).(pulumi.StringOutput)
}

type DatadogMetricStatusConditionsArrayOutput struct{ *pulumi.OutputState }

func (DatadogMetricStatusConditionsArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]DatadogMetricStatusConditions)(nil)).Elem()
}

func (o DatadogMetricStatusConditionsArrayOutput) ToDatadogMetricStatusConditionsArrayOutput() DatadogMetricStatusConditionsArrayOutput {
	return o
}

func (o DatadogMetricStatusConditionsArrayOutput) ToDatadogMetricStatusConditionsArrayOutputWithContext(ctx context.Context) DatadogMetricStatusConditionsArrayOutput {
	return o
}

func (o DatadogMetricStatusConditionsArrayOutput) Index(i pulumi.IntInput) DatadogMetricStatusConditionsOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) DatadogMetricStatusConditions {
		return vs[0].([]DatadogMetricStatusConditions)[vs[1].(int)]
	}).(DatadogMetricStatusConditionsOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DatadogMetricSpecInput)(nil)).Elem(), DatadogMetricSpecArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DatadogMetricSpecPtrInput)(nil)).Elem(), DatadogMetricSpecArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DatadogMetricStatusInput)(nil)).Elem(), DatadogMetricStatusArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DatadogMetricStatusPtrInput)(nil)).Elem(), DatadogMetricStatusArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DatadogMetricStatusConditionsInput)(nil)).Elem(), DatadogMetricStatusConditionsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DatadogMetricStatusConditionsArrayInput)(nil)).Elem(), DatadogMetricStatusConditionsArray{})
	pulumi.RegisterOutputType(DatadogMetricSpecOutput{})
	pulumi.RegisterOutputType(DatadogMetricSpecPtrOutput{})
	pulumi.RegisterOutputType(DatadogMetricStatusOutput{})
	pulumi.RegisterOutputType(DatadogMetricStatusPtrOutput{})
	pulumi.RegisterOutputType(DatadogMetricStatusConditionsOutput{})
	pulumi.RegisterOutputType(DatadogMetricStatusConditionsArrayOutput{})
}
